spring:
  application:
  name: resume-builder
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:resumeDb
    username: resume
    password: p@ssw0rd!567
server:
  servlet:
    context-path: /
